SistemBroche.AplicacionWeb/Models/ErrorViewModel.cs
namespace SistemBroche.AplicacionWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemBroche.AplicacionWeb/Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemBroche.AplicacionWeb.Controllers
{
    public class ContactoController : Controller
    {
        public IActionResult Contacto()
        {
            return View();
        }
    }
}

SistemBroche.AplicacionWeb/Controllers/EventosController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemBroche.AplicacionWeb.Controllers
{
    public class EventosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemBroche.AplicacionWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemBroche.AplicacionWeb.Models;
using System.Diagnostics;

namespace SistemBroche.AplicacionWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemBroche.AplicacionWeb/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemBroche.AplicacionWeb.Controllers
{
    public class InicioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemBroche.AplicacionWeb/Controllers/LugaresController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemBroche.AplicacionWeb.Controllers
{
    public class LugaresController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemBroche.AplicacionWeb/Views/Contacto/contacto.cshtml
@{
    ViewData["Title"] = "Contacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid py-5">
    <div class="container">
        <div class="section-title">
            <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">Contacto</h4>
            <h1 class="display-4">Envianos Tus Datos</h1>
        </div>
        <div class="row">
            <div class="col-lg-4 py-0 py-lg-5">
                <h1 class="mb-3">Nuestros eventos</h1>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Eventos empresariales</h5>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Eventos Sociales</h5>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Eventos Institucionales</h5>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Catering</h5>
                <a href="" class="btn btn-secondary font-weight-bold py-2 px-4 mt-2">Leer mas</a>

            </div>

            <div class="col-lg-4 py-5 py-lg-0" style="min-height: 500px;">
                <div class="position-relative h-100">
                    <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
                    <script>
                        hbspt.forms.create({
                            region: "na1",
                            portalId: "43674721",
                            formId: "ba008662-e087-4831-ad0f-c5b0794544af"
                        });
                    </script>

                </div>
            </div>
            <div class="col-lg-4 py-0 py-lg-5">
                <h1 class="mb-3">Nuestros servicios</h1>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Atencion al cliente</h5>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Servicio Profesional</h5>
                <h5 class="mb-3"><i class="fa fa-check text-primary mr-3"></i>Turismo Sostenible</h5>
                <a href="" class="btn btn-primary font-weight-bold py-2 px-4 mt-2">Leer mas</a>
                
            </div>

        </div>
    </div>

</div>

SistemBroche.AplicacionWeb/Views/Eventos/Index.cshtml
@{
    ViewData["Title"] = "eventos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Service Start -->
<div class="container-fluid pt-5">
    <div class="container">
        <div class="section-title">
            <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">Nuestros eventos</h4>
            <h1 class="display-4">Selecciona el tuyo</h1>
        </div>
        <div class="row">
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/service-1.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-truck service-icon"></i>Eventos sociales</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/service-2.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-coffee service-icon"></i>Eventos Empresariales</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/service-3.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-award service-icon"></i>Eventos Institucionales</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/service-4.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-table service-icon"></i>Catering</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service End -->

SistemBroche.AplicacionWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemBroche.AplicacionWeb/Views/Inicio/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Service Start -->
    <div class="container-fluid pt-5">
        <div class="container">
            <div class="section-title">
                <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">Nuestros servicios</h4>
                <h1 class="display-4">Algo De Lo Nuestro</h1>
            </div>
            <div class="row">
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            
                                <img class="img-fluid mb-3 mb-sm-0 service-image" src="img/service-1.jpg" alt="" onclick="cambiarImagen(this, 1)">
                            
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fas fa-coffee service-icon"></i> Reposteria</h4>
                        <p class="m-0">
                            Nuestra Repostería: un mundo de sabores y creatividad. Desde pasteles artesanales hasta galletas crujientes, cada creación es una obra maestra. Satisfacemos tus antojos diarios y celebramos momentos especiales
                        </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                            
                                <img class="img-fluid mb-3 mb-sm-0 service-image" src="img/service-2.jpg" alt="" onclick="cambiarImagen(this, 2)">
                           
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fas fa-utensils service-icon"></i> Platos Fuertes</h4>
                        <p class="m-0">
                            Nuestros platos son una deliciosa sinfonía de sabores que te transportarán a lugares lejanos. Desde exquisitos mariscos hasta suculentos cortes de carne, cada bocado es una aventura culinaria única.
                        </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                        <a>
                                <img class="img-fluid mb-3 mb-sm-0 service-image" src="img/service-3.jpg" alt="" onclick="cambiarImagen(this, 3)">
                           </a>
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fas fa-cocktail service-icon"></i> Licores</h4>
                        <p class="m-0">
                            Nuestros licores son la expresión de la pasión destilada. Cada botella es un viaje sensorial, desde licores suaves hasta destilados audaces, que deleitarán su paladar y despiertan los sentidos
                        </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="row align-items-center">
                        <div class="col-sm-5">
                           
                                <img class="img-fluid mb-3 mb-sm-0 service-image" src="img/servicio.jpg" alt="" onclick="cambiarImagen(this, 4)">
                          
                        </div>
                        <div class="col-sm-7">
                            <h4><i class="fas fa-hand-holding-heart service-icon"></i> Servicio</h4>
                        <p class="m-0">
                            Nuestro servicio ofrece soluciones innovadoras y eficientes, brindando satisfacción a nuestros clientes y mejorando sus experiencias. Descubre la excelencia con nosotros.
                        </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const imagenesSecciones = [
            "img/service-1.jpg",
            "img/plato.jpg",
            "img/chef.jpg",
            "img/service-2.jpg",
            "img/plato.jpg",
            "img/chef.jpg",
            "img/service-3.jpg",
            "img/plato.jpg",
            "img/chef.jpg",
            "img/service-4.jpg",
            "img/plato.jpg",
            "img/chef.jpg",
        ];

        let indiceImagenes = [0, 0, 0, 0];

        function cambiarImagen(imgElement, seccion) {
            const nuevaImagen = imagenesSecciones[(seccion - 1) * 3 + indiceImagenes[seccion - 1]];
            imgElement.src = nuevaImagen;
            indiceImagenes[seccion - 1] = (indiceImagenes[seccion - 1] + 1) % 3;
        }
    </script>

<!-- Service End -->
<!-- Testimonial Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="section-title">
            <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">Testimonios</h4>
            <h1 class="display-4">Lo que dicen de nosotros</h1>
        </div>
        <div class="owl-carousel testimonial-carousel">
            <div class="testimonial-item">
                <div class="d-flex align-items-center mb-3">
                    <img class="img-fluid" src="img/testimonial-1.jpg" alt="">
                    <div class="ml-3">
                        <h4>Carolina</h4>
                        <i>Agente de viajes </i>
                        <p class="m-0">
                            La celebracion de fin de año fue la mejor!
                        </p>
                    </div>
                </div>
                <p class="m-0"></p>
            </div>
            <div class="testimonial-item">
                <div class="d-flex align-items-center mb-3">
                    <img class="img-fluid" src="img/testimonial-2.jpg" alt="">
                    <div class="ml-3">
                        <h4>Andres</h4>
                        <i>Desarrollador</i>
                        <p class="m-0">
                        la presentacion de proyectos fue increible, muy buena organizacion.
                        </p>
                    </div>
                </div>
                <p class="m-0"></p>
            </div>
            <div class="testimonial-item">
                <div class="d-flex align-items-center mb-3">
                    <img class="img-fluid" src="img/testimonial-3.jpg" alt="">
                    <div class="ml-3">
                        <h4>Katerine</h4>
                        <i>Ingeniero Civil</i>
                        <p class="m-0">
                            la reunion de bienvenida fue grandiosa, no habia probado un postre asi.
                        </p>
                    </div>
                </div>
                <p class="m-0"></p>
            </div>
            <div class="testimonial-item">
                <div class="d-flex align-items-center mb-3">
                    <img class="img-fluid" src="img/testimonial-4.jpg" alt="">
                    <div class="ml-3">
                        <h4>Fernando</h4>
                        <i>Ingeniero Sistemas</i>
                        <p class="m-0">
                           El grado de la universidad fue muy bueno, volvere para mi matrimonio.
                        </p>
                    </div>
                </div>
                <p class="m-0"></p>
            </div>
        </div>
    </div>
</div>

SistemBroche.AplicacionWeb/Views/Lugares/Index.cshtml
@{
    ViewData["Title"] = "Lugares";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid pt-5">
    <div class="container">
        <div class="section-title">
            <h4 class="text-primary text-uppercase" style="letter-spacing: 5px;">Nuestros Lugares</h4>
            <h1 class="display-4">Reserva segun disponibilidad</h1>
        </div>
        <div class="row">
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/lugar1.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-truck service-icon"></i>Villa conjunto</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/lugar2.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-coffee service-icon"></i>Casa lago</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/lugar3.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-award service-icon"></i>Rio</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-5">
                <div class="row align-items-center">
                    <div class="col-sm-5">
                        <img class="img-fluid mb-3 mb-sm-0" src="img/lugar4.jpg" alt="">
                    </div>
                    <div class="col-sm-7">
                        <h4><i class="fa fa-table service-icon"></i>valle de la calma</h4>
                        <p class="m-0">
                            Sit lorem ipsum et diam elitr est dolor sed duo. Guberg sea et et lorem dolor sed est sit
                            invidunt, dolore tempor diam ipsum takima erat tempor
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SistemBroche.AplicacionWeb/Views/Reposteria/Reposteria.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SistemBroche.AplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Broche de oro</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free Website Template" name="keywords">
    <meta content="Free Website Template" name="description">

    <!-- Favicon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    @await RenderSectionAsync("Estilos", required: false)
</head>
<body>
    <!-- Navbar Start -->
    <div class="container-fluid p-0 nav-bar">
        <nav class="navbar navbar-expand-lg bg-none navbar-dark py-3">
            <a class="navbar-brand" href="#">
                <img class="logo" src="img/broche.png" alt="Image">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto p-4">
                    <a href="@Url.Action("Index","Inicio")" class="nav-item nav-link">Inicio</a>
                    <a href="@Url.Action("Contacto","Contacto")" class="nav-item nav-link">Contacto</a>
                    <a href="@Url.Action("Index","Lugares")" class="nav-item nav-link">Nuestros Lugares</a>
                    <a href="@Url.Action("Index","Eventos")" class="nav-item nav-link">Eventos</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->
    <!-- Carousel Start -->
    <div class="container-fluid p-0 mb-5">
        <div id="blog-carousel" class="carousel slide" data-ride="carousel">
            <!-- Eliminado "overlay-bottom" -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="w-100" src="img/fuego.jpg" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="text-primary font-weight-medium m-0"></h2>
                        <h1 class="display-1 text-white m-0"></h1>
                        <h2 class="text-white m-0"></h2>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="img/fuego.jpg" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="text-primary font-weight-medium m-0"></h2>
                        <h1 class="display-1 text-white m-0"></h1>
                        <h2 class="text-white m-0"></h2>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="img/fuego.jpg" alt="Image">
                    <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                        <h2 class="text-primary font-weight-medium m-0"></h2>
                        <h1 class="display-1 text-white m-0"></h1>
                        <h2 class="text-white m-0"></h2>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#blog-carousel" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#blog-carousel" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
    <!-- Carousel End -->
 
    <!-- Page Header End -->
    
    <div class="container-fluid">
     @RenderBody()
    </div>

    <!-- Footer Start -->
    <div class="container-fluid footer text-white mt-5 pt-5 px-0 position-relative overlay-top">
        <div class="row mx-0 pt-5 px-sm-3 px-lg-5 mt-4">
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">Get In Touch</h4>
                <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                <p class="m-0"><i class="fa fa-envelope mr-2"></i>info@example.com</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">Follow Us</h4>
                <p>Amet elitr vero magna sed ipsum sit kasd sea elitr lorem rebum</p>
                <div class="d-flex justify-content-start">
                    <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-lg btn-outline-light btn-lg-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-lg btn-outline-light btn-lg-square" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">Open Hours</h4>
                <div>
                    <h6 class="text-white text-uppercase">Monday - Friday</h6>
                    <p>8.00 AM - 8.00 PM</p>
                    <h6 class="text-white text-uppercase">Saturday - Sunday</h6>
                    <p>2.00 PM - 8.00 PM</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h4 class="text-white text-uppercase mb-4" style="letter-spacing: 3px;">Newsletter</h4>
                <p>Amet elitr vero magna sed ipsum sit kasd sea elitr lorem rebum</p>
                <div class="w-100">
                    <div class="input-group">
                        <input type="text" class="form-control border-light" style="padding: 25px;" placeholder="Your Email">
                        <div class="input-group-append">
                            <button class="btn btn-primary font-weight-bold px-3">Sign Up</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid text-center text-white border-top mt-4 py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
            <p class="mb-2 text-white">Copyright &copy; <a class="font-weight-bold" href="#">Domain</a>. All Rights Reserved.</a></p>
            <p class="m-0 text-white">Designed by <a class="font-weight-bold" href="https://htmlcodex.com">HTML Codex</a></p>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>


</html>
@*@RenderBody()
@await RenderSectionAsync("scripts", required: false)*@